name: "Now's the Time"
favicon: null
layout_spectrum: 0.85375
typography_spectrum: 0.7131927201990038
title: "Now's the Time Jazz Quintet"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181619'
    - '#fefefe'
    - '#d4d8e1'
    - '#3a4e45'
    - '#99989e'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.17200125590898097
  rhythmicContrast: 0.5
purpose: []
