name: "Now's the Time"
favicon: null
layout_spectrum: 0.6444191613700241
typography_spectrum: 0.7131927201990038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a0e'
    - '#333d46'
    - '#dd6660'
    - '#95a4c5'
    - '#f9bea1'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.17200125590898097
  rhythmicContrast: 0.25
purpose: []
